cmd/model-agent/main.go
pkg/hfutil/hub/constants.go
pkg/hfutil/hub/constants_test.go
pkg/hfutil/hub/download.go
pkg/hfutil/hub/module.go
pkg/hfutil/hub/repo.go
pkg/modelagent/gopher.go
site/content/en/docs/administration/model-agent.md
site/content/en/docs/concepts/base_model.md

/kind bug
This PR fixes multiple critical issues in the model-agent that were preventing proper model downloads and management in production environments:
- Added permission for model-agent to access secrets at cluster scope
- Previously failing with "secrets is forbidden" errors
- Implemented proper rate limit handling with exponential backoff and jitter
- Added Retry-After header parsing for server-suggested delays
- Prevents thundering herd problem in large clusters with many agents
- Fixed crashes in progress logging when progressManager.logger was nil
- Added proper nil checks throughout the codebase
- Fixed incorrect path construction during model deletion
- Now uses consistent `getDestPath()` for both download and delete operations
- Made secret key name configurable via model …

[bugfix] fix hf token fetch and deletion logic

---

site/content/en/docs/concepts/serving_runtime.md

/kind documentation
As "SRT" is already the abbreviation for "SGLang Runtime", this PR updates the documentation to consistently use "SGLang Runtimes" instead of "SRT (SGLang) Runtimes".
Fixes #
```release-note
```

Renames SRT to SGLang for clarity

---

cmd/model-agent/main.go
pkg/hfutil/hub/constants.go
pkg/hfutil/hub/constants_test.go
pkg/hfutil/hub/download.go

/kind bug
This PR fixes critical issues with the model agent that were causing infinite download loops and download failures for large models:
1. **Infinite Download Loop Fix**: The model agent was updating ClusterBaseModel specs after parsing model configurations, which triggered other agents to re-download
the same model. This created an infinite loop where models were continuously downloaded. Fixed by preventing model agents from updating the ClusterBaseModel CRD.
2. **Download Timeout Fix**: Large model files (>10GB) were failing with "context deadline exceeded" errors because the HTTP client timeout was set to only 10
minutes. Increased the timeout to 2 hours to accommodate large model downloads.
3. **Race Condition Fix**: Multiple workers downloading the same model could encounter a …

[bugfix] fix: resolve model agent download loops and timeout issues

---

charts/ome-resources/templates/model-agent-daemonset/daemonset.yaml
charts/ome-resources/templates/ome-controller/deployment.yaml
charts/ome-resources/values.yaml

- Adds global imagePullSecrets configuration to the ome-resources Helm chart
- Enables deployment to environments with private container registries
- Added `global.imagePullSecrets` configuration option to `values.yaml` with example usage
- Updated model-agent daemonset template to use global imagePullSecrets
- Updated ome-controller deployment template to use global imagePullSecrets

feat(helm): Add imagePullSecrets support to ome-resources chart

---

.github/workflows/helm-gh-pages.yaml

- Fixed indentation in heredoc content that was causing YAML syntax error on line 123

Fix YAML syntax error in helm workflow

---

pkg/constants/constants.go
pkg/modelagent/scout.go
pkg/modelagent/scout_test.go

Replace deprecated beta.kubernetes.io/instance-type label with the GA
node.kubernetes.io/instance-type label for node instance type detection.
The code now tries the newer label first using the ok value from map
lookup and falls back to the deprecated beta label for backward
compatibility. This ensures the code works with both old and new
Kubernetes versions while preferring the non-deprecated label when
available.
The deprecated label constant has been moved to pkg/constants for
better maintainability.

fix: use non-deprecated node instance type label

---

charts/ome-resources/templates/model-agent-daemonset/daemonset.yaml
config/model-agent/daemonset.yaml

Increase initialDelaySeconds for health checks from 5 to 60 seconds to prevent
restart loops caused by the interaction between node-specific startup jitter
and insufficient health check delays.
The model-agent implements startup jitter to prevent thundering herd problems
when multiple agents start simultaneously (see cmd/model-agent/main.go:227-237).
This jitter creates a deterministic but distributed delay of 0-30 seconds per
node based on a hash of the node name:
```go
// cmd/model-agent/main.go:233-234
// Create delay between 0-30 seconds based on node name
jitterDelay := time.Duration(hash%30) * time.Second
```
However, health checks were configured with only 5 seconds initialDelaySeconds,
causing them to start checking before the application finished initializing.
This created a race …

Fix model-agent health check timing to account for startup jitter

---

cmd/ome-agent/replica_agent.go
internal/ome-agent/replica/config.go
internal/ome-agent/replica/config_test.go
internal/ome-agent/replica/module.go
internal/ome-agent/replica/module_test.go
internal/ome-agent/replica/replica.go
internal/ome-agent/replica/replica_test.go
pkg/ociobjectstore/config.go
pkg/ociobjectstore/config_test.go
pkg/ociobjectstore/module.go
pkg/ociobjectstore/module_test.go

/kind bug
This PR updates the object replication workflow to use separate Object Storage clients for downloading and uploading objects, improving both security and maintainability.
**Background:** 
We want to ensure that customers do not have direct write access to the customer model store bucket. Granting write permissions would allow users operating with OBO (On-Behalf-Of) tokens to directly overwrite or modify data in the model store, which introduces significant security and data integrity risks. By clearly separating client responsibilities - one for downloading with customer-level credentials and one for uploading with service-level credentials - we prevent unauthorized or accidental data modifications by customers. This approach also provides stronger isolation of permissions and …

[bugfix] Separate OCI Object Storage clients for ome agent

---

pkg/controller/v1beta1/inferenceservice/cleanup.go
pkg/controller/v1beta1/inferenceservice/cleanup_test.go
pkg/controller/v1beta1/inferenceservice/components/base.go
pkg/controller/v1beta1/inferenceservice/components/component.go
pkg/controller/v1beta1/inferenceservice/components/decoder.go
pkg/controller/v1beta1/inferenceservice/components/engine.go
pkg/controller/v1beta1/inferenceservice/components/router.go
pkg/controller/v1beta1/inferenceservice/controller.go

/kind cleanup
/kind bug
This PR refactors the InferenceService controller to fix a Kubernetes reconciliation anti-pattern where "deletion reconcilers" were being created
with nil specs when components (router, decoder, engine) were removed from the InferenceService spec.
**Previous behavior (problematic):**
- When a component was removed from the spec, the controller created a reconciler with a nil spec to handle deletion
- Used status-based existence checking (unreliable)
- Manually deleted resources instead of leveraging Kubernetes garbage collection
- Created unnecessary reconciler instances for deletion
**New behavior (fixed):**
- Resources are immediately cleaned up when components are removed from the spec
- Uses label-based selection with owner reference verification
- Dynamically …

[misc] refactor component cleanup

---

Makefile
config/models/kustomization.yaml

/kind bug
When I exec `make install`:
```shell
🔄 Step 4: Applying cluster resources...
kubectl apply --server-side --force-conflicts -k config/clusterresources
error: accumulating resources: accumulation err='accumulating resources from '../models': '/root/OME/ome/config/models' must resolve to a file': recursed accumulation of path '/root/OME/ome/config/models': accumulating resources: accumulation err='accumulating resources from 'meta/llama-4-maverick-17b-128e-instruct-fp8.yaml': evalsymlink failure on '/root/OME/ome/config/models/meta/llama-4-maverick-17b-128e-instruct-fp8.yaml' : lstat /root/OME/ome/config/models/meta/llama-4-maverick-17b-128e-instruct-fp8.yaml: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on …
```

[Bugfix] Fix models yaml file no such file or directory

---

site/static/images/ome-architecture.html
site/static/images/ome-architecture.svg

/kind documentation
Fix the title name for the architecture diagram in doc
Fixes #
```release-note
```

[DOC]Fix doc architecture diagram SVG title

---

cmd/ome-agent/replica_agent.go
cmd/ome-agent/replica_agent_test.go
internal/ome-agent/replica/oci_to_oci.go
pkg/ociobjectstore/module.go
pkg/ociobjectstore/module_test.go

/kind cleanup + minor_updates
Making some improvements (suggested by genmini-code-assist in #157) and cleanup to replica ome-agent
1. Removed the usage of `panic` in replica_agent.go to avoid the application from crashing unexpectedly;
2. Let an error return when it is not a complete successful replication in oci_to_oci.go, i.e., failed the application when a partial or total failure during replication tasks;
3. Cleaned up unused/duplicate code in ociobjectstore module;
4. Added unit tests for functions in replica_agent.go.
Tested in local.
For the above change #2, tested after the change, a partial failure will let the application fail with exit code 1.

[Misc] replica ome-agent: minor improvements + cleanup

---

oeps/0004-pvc-storage-support/README.md
oeps/0004-pvc-storage-support/oep.yaml

/kind design
This PR introduces the design specification for PVC (Persistent Volume Claim) storage support in OME's model management system. The design enables BaseModel and ClusterBaseModel resources to reference models stored in Kubernetes PVCs without requiring downloads to host paths.
Key aspects of the design:
- **Simplified Architecture**: Model agent completely skips PVC storage types, with all handling done by the BaseModel controller
- **Metadata Extraction**: Uses ephemeral Kubernetes Jobs to mount PVCs and extract model metadata
- **Native K8s Scheduling**: Leverages Kubernetes' built-in PVC scheduling instead of custom node labeling
- **Support for Both Access Modes**: Works with both ReadWriteMany (RWX) and ReadWriteOnce (RWO) PVCs
The design addresses the common use case …

[oep] add pvc storage support

---

pkg/modelagent/gopher.go
pkg/modelagent/gopher_test.go
pkg/modelagent/scout.go

/kind feature
This PR implements the model agent changes needed for PVC storage support as outlined in OEP-0004. Specifically, it updates the model agent
(`gopher.go` and `scout.go`) to skip processing of PVC storage types entirely.
**Changes made:**
- Added detection logic for PVC storage type using `storage.GetStorageType()`
- Model agent now returns immediately when encountering PVC storage URIs (format: `pvc://{pvc-name}/{sub-path}`)
- Added informational logging when PVC models are skipped
- Ensured no ConfigMap updates or node labels are created for PVC storage
- Added unit tests to verify PVC skip behavior
**Why this is needed:**
PVC storage requires a fundamentally different approach than downloadable storage types. Since DaemonSet pods cannot effectively mount PVCs
(especially …

[core] skip model agent task for pvc storage

---

cmd/ome-agent/k8sclient.go
cmd/ome-agent/main.go
cmd/ome-agent/model_metadata_agent.go
cmd/ome-agent/model_metadata_agent_test.go
config/ome-agent/model-metadata.yaml
hack/test-model-metadata-agent.sh
internal/ome-agent/model-metadata/config.go
internal/ome-agent/model-metadata/metadata.go
internal/ome-agent/model-metadata/metadata_test.go
internal/ome-agent/model-metadata/module.go

/kind feature
This PR implements the model metadata extraction agent as part of OEP-0004 (PVC Storage Support). The new `model-metadata` agent enables OME to
extract metadata from models stored in Kubernetes PVCs without requiring the model to be downloaded or accessible via object storage.
**Key changes:**
- Added new `model-metadata` agent to the ome-agent framework that can be run as a Kubernetes Job
- Implemented metadata extraction using the existing `hfutil/modelconfig` parser for robust support of 20+ model types
- Created internal business logic module following established ome-agent patterns
- Added support for both BaseModel and ClusterBaseModel CRs with proper namespace handling
- Implemented automatic capability inference (text-generation, vision, embeddings) based on model …

[core] add model metadata parser to ome agent

---

pkg/utils/instance_type_util.go

Added the gd-8xh200ib-i128 shape mapping for H200 GPUs to support
CoreWeave's H200 instance types.

[utils] Add CoreWeave H200 shape configuration

---

pkg/hfutil/modelconfig/kimi_k2.go
pkg/hfutil/modelconfig/kimi_k2_test.go
pkg/hfutil/modelconfig/testdata/kimi_k2_instruct.json
pkg/modelagent/gopher.go

/kind feature
This PR adds support for the Kimi-K2-Instruct model from Moonshot AI to the OME model configuration parser.
1. **Added Kimi-K2 model configuration support** (`pkg/hfutil/modelconfig/kimi_k2.go`):
2. **Added comprehensive tests** (`pkg/hfutil/modelconfig/kimi_k2_test.go`):
3. **Added test data** (`pkg/hfutil/modelconfig/testdata/kimi_k2_instruct.json`):
4. **Improved error handling** in `pkg/modelagent/gopher.go`:
Fixes #
- The Kimi-K2 model uses `model_type: "kimi_k2"` but architectures `["DeepseekV3ForCausalLM"]`, which is why it shares many configuration fields with DeepSeek V3
- The parameter count is set to 1.5T based on the model documentation and the increased expert count (384 vs 256 in DeepSeek V3)
- This change enables the model agent to properly parse Kimi-K2 model …

[core] add kimi k2 model support

---

cmd/manager/main.go
cmd/model-agent/main.go
cmd/multinode-prober/multinode_prober.go
cmd/ome-agent/main.go
pkg/version/version.go

/kind bug
As the title suggests, the current implementation lacks the pkg/version package, but it has been used in multiple Dockerfiles.
In addition, it is also necessary to add the required version log information during the startup stage.
Fixes https://github.com/sgl-project/ome/issues/189
NONE

fix: 🔧  Missing pkg/version package.

---

config/runtimes/srt/deepseek-rdma-pd-rt.yaml
config/runtimes/srt/kimi-k2-pd-rt.yaml
config/samples/isvc/meta/llama-4-maverick-17b-128e-instruct-fp8.yaml
pkg/controller/v1beta1/inferenceservice/cleanup.go

/kind bug
/kind cleanup
- fix external service being cleaned up
- update latest kimi runtime
Fixes #
```release-note
```

[misc] fix external service being cleaned up and kimi runtime update

---

pkg/controller/v1beta1/benchmark/utils/utils.go
pkg/controller/v1beta1/benchmark/utils/utils_test.go

/kind bug
Storage is required by BenchmarkJob but command line arguments was changed. 
https://github.com/sgl-project/ome/issues/238
Fixes #
```release-note
```

[BUG]Fix BenchmarkJob Deprecated Storage Command

---

charts/ome-resources/README.md
charts/ome-resources/templates/model-agent-daemonset/daemonset.yaml
charts/ome-resources/values.yaml

Users may need to mount additional config, scratch space, or secrets into the model-agent DaemonSet pods. This change exposes `modelAgent.extraVolumes` and `modelAgent.extraVolumeMounts` in the Helm values so integrators can supply arbitrary volumes/mounts without forking the chart.
Changes:
- Template `extraVolumes` under `spec.template.spec.volumes`.
- Template `extraVolumeMounts` under container `volumeMounts`.
- Add values with docs and examples in `values.yaml`.
- Document new values in README.
- Minor whitespace cleanup in daemonset template.
No breaking changes; defaults keep behavior unchanged.

Support extra volumes and mounts in model-agent

---

pkg/storage/options.go
pkg/storage/providers/oci/provider.go
pkg/storage/providers/s3/integrity.go
pkg/storage/providers/s3/multipart.go
pkg/storage/providers/s3/parallel.go
pkg/storage/providers/s3/presigned.go
pkg/storage/providers/s3/provider.go
pkg/storage/utils.go

/kind feature
- Added parallel download support for large files (>100MB) to improve performance
- Fixed critical issue where S3 provider incorrectly handled file vs directory targets during downloads
- Implemented all missing download options for feature parity with OCI provider
- Enhanced test suite with comprehensive coverage for all download scenarios
Implemented s3 provider multi-threaded downloads for large files to significantly improve download performance:
- Automatically triggers for files >100MB
- Uses configurable number of workers (default: 4)
- Downloads file in chunks with concurrent goroutines
- Properly handles partial content with byte ranges
- Includes progress reporting for each chunk
```go
// Parallel download for large files
if *obj.Size > 100*1024*1024 && …
```

[core] add s3 and minio storage provider and download option support

---

pkg/xet/Makefile
pkg/xet/build/Dockerfile

/kind feature
/kind build
1. Added a Dockerfile under pkg/xet/build/ to enable Linux build of the XET Rust binding library. 
2. Updated Makefile
No

[Misc] Add Dockerfile for XET Rust binding linux build

---

.gitignore

This static library created by local build, it don't need to upload in repo.
None.

[Misc]add static library .a in gitignore
